### PR TITLE
Adding parseInput function parameter

### PR DESCRIPTION
**Pull request by jesusr**
Before search, this function parse the users search input. Very useful for special characters that should match with every similar character.

And clean some jsHint alerts.

### CODE REVIEW

**Comment by javisr** [comment]
+1

**Comment by ghiden** [comment]
How would you use this?

**Comment by jesusr** [comment]
I am using this like this:

- dir.html
```html
<angucomplete-alt ... parse-input="**accentsTidy**"></angucomplete-alt>
´´´
accentsTidy is a scope function:

- ctrl.js
```javascript
$scope.accentsTidy = function(s) {
      var r = s.toLowerCase();
      r = r.replace(new RegExp('[àáâãäå]', 'g'), 'a');
      ...
      return r;
 }
´´´

So the search string are parsed before the match process.

**Comment by LauraAlb** [comment]
:+1:

**Comment by luisromangz** [comment]
:+1:

**Comment by ghiden** [comment]
One last question, would this work with match-class?

**Comment by jesusr** [comment]
@ghiden I find no reason for not doing so.

**Comment by ghiden** [comment]
@jesusr Can you add description to README?

**Comment by jesusr** [comment]
@ghiden done ;)

**Comment by ghiden** [comment]
@jesusr Thank you.

**Comment by Nesta** [comment]
Great!

**Pull request merged**
