### PR TITLE
Add focusFirst attribute. fixes #92

### LINKED ISSUE #92: First match automatically gets focused
Can you add the same feature to automatically focus the first match from the dropdown list like the angular bootstrap ui typeahead?

http://angular-ui.github.io/bootstrap/#/typeahead
typeahead-focus-first (Defaults: true) : Should the first match automatically be focused as you type

### PR DESCRIPTION
**Pull request by Freezystem**
Allow the use of `focus-first="true"` attribute to automatically select the first matching result.

### CODE REVIEW

**Comment by ghiden** [comment]
Thanks for the PR.
Can you add some tests and remove minified js?

**Comment by Freezystem** [comment]
I have written down a test but I'll be more comfortable if you take a look a it as it's my first official try to write one. I've also removed the minified JS.

**Comment by ghiden** [comment]
Thanks for the changes. I'll have a look.

**Comment by Freezystem** [comment]
Ok, I've rewritten the test because it was poorly written. I was unable to launch them by the time I wrote them at work (issue with my computer). Now its working properly. Sorry for that.

**Comment by Freezystem** [comment]
any update on that PR ?

**Pull request merged**
