### PR TITLE
Added search string to scope.

### PR DESCRIPTION
**Pull request by ryanflowers**
Moved search string to the scope to allow for override outside of the directive. This allows to have the search box live anywhere. No assumptions are made about the template.

### CODE REVIEW

**Comment by ghiden** [comment]
I don't understand the use cases for this change.
I think directives should be self-contained.
If input is not part of this directive, what is it trying to autocomplete?

**Comment by Boshen** [comment]
@ghiden I don't understand the use case either. But at least you can merge in that `unbindMousedown`, I detected a memory leak a long time ago and I think this is it :-)

**Comment by ryanflowers** [comment]
The use case is that you provide the ability to use your own template but then make assumptions about what is in it. The template is just the view. Removing the assumptions about what is in the view makes the directive much more extendable. Lets the user build the view of the directive as they see fit. It doesn't make it any less "self contained", not sure I follow the correlation there. You are already providing most of the functionality to override. Which is the whole purpose of allowing template injection. This way the input can live anywhere in the DOM and the auto complete can still be used. What if the users wants to use something like CKEditor(in my case) to drive the autocomplete, or even a service? Removing these assumptions allows for all of this at no cost.

**Comment by ghiden** [comment]
Are you trying to use this directive without template?
Could you create a jsbin or plunkr example? Probably it's easier to see how you would use this feature.

**Comment by jrgleason** [comment]
I think I may have had a similar need. My use case is that I have a search box with auto complete. If there is no item found in the searchable items, we may want to assume it can be added. In my case I give a list of labels and if I want to move on without one selected it is ok. However, I still need to pass that info back to the eventual POST. I am going to hack this by using the change event.

**Pull request closed without merging**
