### PR TITLE
Add custom function support for remote data

### PR DESCRIPTION
**Pull request by jbuquet**
Just wanted to use the directive consuming an endpoint through an ngResource so that I make use of many configurations I have in it.

### CODE REVIEW

**Comment by ghiden** [comment]
Thanks @jbuquet 
I merged your PR.
I changed the attribute name and added a test.

**Comment by jbuquet** [comment]
Thanks @ghiden great work

**Comment by marook** [comment]
I stumbled over the 'responseData = responseData.data;' unpacking which has been introduced with this pull request. I wonder why you unpack the data property from the resolved promise?

**Comment by jbuquet** [comment]
Hi @marook 

I don't see that code on my commit, and sincerely I can't remember exactly what I did.

Can you explain further where you see such code and confirm it was introduced with this pr?

Thanks :)

**Comment by ghiden** [comment]
@marook It was me. When it is remote api handler, I chain the promise with 'then' which returns a HttpPromise object. But when in other parts I use 'success' and 'error' methods which have different signatures. So, the line that you spotted is for normalize these differences.

**Comment by marook** [comment]
OK... I understand. I was just curious because we are using the custom handler callback with our own function which generates the data dynamically. So we don't fetch our data directly from $http and that's the reason why our data at first had no data property.

Thanks for the feedback :+1:

**Comment by marook** [comment]
For completeness... the code I was referring to is https://github.com/ghiden/angucomplete-alt/commit/50547098fdc9e56ccc4371f0d5774c97553a4e67#diff-0b23162bfe8cb996d24ae2980605b539R410

**Pull request merged**
