### PR TITLE
you can merge multiple array to one array. Then you can show result.

### PR DESCRIPTION
**Pull request by mahmutduva**

### CODE REVIEW

**Comment by ghiden** [comment]
I really don't see the benefit of doing this. You should just merge the result when you receive it from remote API.

**Comment by mahmutduva** [comment]
Yes, it is for remote API. My example is simulate API that have multiple array in object. Maybe developers will use this feature when they want to merge a few array.

**Comment by ghiden** [comment]
What I'm trying to say is that you don't need to modify extractValue function. Just use your searchConcatData to merge the response.

**Comment by ghiden** [comment]
This can be all done in remote-api-handler.

**Pull request closed without merging**
