### PR TITLE
 Behavior of Select Element #34 

### PR DESCRIPTION
**Pull request by DarkReZuS**
add option "show-on-select" to display drop-down list on focus for localdata. Value is max number of element to display.

### CODE REVIEW

**Comment by DarkReZuS** [comment]
looks similar to #91

**Comment by ghiden** [comment]
This feature is more involved than your implementation. After you select something, lose focus and then focus again, then it shows everything. But it should show the selected one and anything that's found in search with the given string. #91 was a bit too much on UI which I don't think not a good fit for general purpose directive like angucomplete-alt.

**Comment by DarkReZuS** [comment]
v0.0.38 fits my needs. thanks.

**Comment by ghiden** [comment]
:smile:

**Pull request closed without merging**
