### PR TITLE
Enable to change the value "initialValue" after loading

### PR DESCRIPTION
**Pull request by alvesseb**
I propose that "initialValue" is not unbind after loading and "initialValue" accept null value.

Thx.

Seb.

### CODE REVIEW

**Comment by ghiden** [comment]
If you keep watching and change accordingly, this won't be initial value anymore.
I can't take this.

**Comment by alvesseb** [comment]
I understand, but in this case how can it be done to modify the value after the initialization?

**Comment by ghiden** [comment]
There is no 2-way binding in this directive. So, you can't change it from parent scope.
Sorry, I'm not planning to change this behavior.

**Comment by alvesseb** [comment]
Too bad , I will implement this behavior in my fork. 
Thank you for your time.

**Comment by ghiden** [comment]
Sorry for that and thank you for understanding.
This directive is getting too feature bloated so I'm trying not to add more complexities.

**Comment by pkorzh** [comment]
hi guys, i'm having the same problem. when the directive is used inside of ngRepeat, ngRepeat will cache the DOM node causing initial value to remain after the model has been changed.

so it would be really nice to have some way to invalidate it.

**Pull request closed without merging**
