### PR TITLE
Return from function throws error instead.

### PR DESCRIPTION
**Pull request by maktwin**
Return from function throws error instead.

### CODE REVIEW

**Comment by maktwin** [comment]
throws error when inputChangeHandler invoked with empty value in input field.

**Comment by ghiden** [comment]
I can probably revert this commit https://github.com/ghiden/angucomplete-alt/commit/33851f44cc09752b65e9c0ab2d9994ca195d4255
#282 was very minor issue.
Could you try removing that commit and see if it throws error or not?

**Comment by maktwin** [comment]
I just now removed that commit 33851f4, and all works fine.

**Comment by ghiden** [comment]
@maktwin Thank you for testing it. I'll revert that commit.

**Pull request closed without merging**
